name: Build GKI Kernel

on:
  workflow_dispatch:
    inputs:
      toolchain:
        description: 'Toolchain'
        required: true
        type: choice
        options:
          - aosp-clang
          - zyc-clang

jobs:
  build-xxksu:
    name: xxKSU nezha ${{ inputs.toolchain }}
    uses: ./.github/workflows/build-xxksu.yml
    with:
      device: nezha
      toolchain: ${{ inputs.toolchain }}

  build-kowsu:
    name: KowSU nezha ${{ inputs.toolchain }}
    uses: ./.github/workflows/build-kowsu.yml
    with:
      device: nezha
      toolchain: ${{ inputs.toolchain }}

  build-kowsu-susfs:
    name: KowSU+SuSFS nezha ${{ inputs.toolchain }}
    uses: ./.github/workflows/build-kowsu-susfs.yml
    with:
      device: nezha
      toolchain: ${{ inputs.toolchain }}

  release:
    needs: [build-xxksu, build-kowsu, build-kowsu-susfs]
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    uses: ./.github/workflows/release.yml
    with:
      release_tag: ${{ github.run_number }}
      kernel_ver: "6.12.23"
      release_title: "Nezha Kernel"
